In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [45,56,67,34,34],
              'col3': "sudhanshu kumar krish ineuron one".split()
     })

In [2]:
pd.DataFrame({'col1':[1,2,3,4,5],
'col2':[45,56,67,78,23],
'col2':"hero nobody someone here how"})

col1                          col2
0     1  hero nobody someone here how
1     2  hero nobody someone here how
2     3  hero nobody someone here how
3     4  hero nobody someone here how
4     5  hero nobody someone here how

In [13]:
df= pd.DataFrame({'col1':[1,2,3,4,5],
'col2':[45,56,67,78,23],
'col3':"hero nobody someone here how".split()
})

In [14]:
df

col1  col2     col3
0     1    45     hero
1     2    56   nobody
2     3    67  someone
3     4    78     here
4     5    23      how

In [15]:
df['col4'] = df['col1']**2

In [16]:
df

col1  col2     col3  col4
0     1    45     hero     1
1     2    56   nobody     4
2     3    67  someone     9
3     4    78     here    16
4     5    23      how    25

In [17]:
df['col5']= df['col3'].str[0]

In [18]:
df

col1  col2     col3  col4 col5
0     1    45     hero     1    h
1     2    56   nobody     4    n
2     3    67  someone     9    s
3     4    78     here    16    h
4     5    23      how    25    h

In [20]:
def test(a):
    return a**2

In [21]:
df['col4_4']= df['col1'].apply(test)

In [22]:
df

col1  col2     col3  col4 col5  col4_4
0     1    45     hero     1    h       1
1     2    56   nobody     4    n       4
2     3    67  someone     9    s       9
3     4    78     here    16    h      16
4     5    23      how    25    h      25

In [23]:
def test1(a):
    if a== 's':
        return 's'
    else:
        return 'z'

In [24]:
df['col6']= df['col5'].apply(test1)

In [25]:
df

col1  col2     col3  col4 col5  col4_4 col6
0     1    45     hero     1    h       1    z
1     2    56   nobody     4    n       4    z
2     3    67  someone     9    s       9    s
3     4    78     here    16    h      16    z
4     5    23      how    25    h      25    z

In [27]:
df['col6_6'] = df['col4'].apply(lambda a:'s' if a=='s' else 'z') 

In [28]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6
0     1    45     hero     1    h       1    z      z
1     2    56   nobody     4    n       4    z      z
2     3    67  someone     9    s       9    s      z
3     4    78     here    16    h      16    z      z
4     5    23      how    25    h      25    z      z

In [29]:
df['col7'] =df['col3'].apply(len)

In [30]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45     hero     1    h       1    z      z     4
1     2    56   nobody     4    n       4    z      z     6
2     3    67  someone     9    s       9    s      z     7
3     4    78     here    16    h      16    z      z     4
4     5    23      how    25    h      25    z      z     3

In [31]:
import math

In [32]:
df['col8']= df['col2'].apply(math.log)

In [33]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45     hero     1    h       1    z      z     4  3.806662
1     2    56   nobody     4    n       4    z      z     6  4.025352
2     3    67  someone     9    s       9    s      z     7  4.204693
3     4    78     here    16    h      16    z      z     4  4.356709
4     5    23      how    25    h      25    z      z     3  3.135494

In [34]:
l = ['hero',1,2,3,4]

In [35]:
type(l)

list

In [36]:
np.array(l)

array(['hero', '1', '2', '3', '4'], dtype='<U11')

In [37]:
type(np.array(l))

numpy.ndarray

In [38]:
 np.array([3,4,5,6,3.0])

array([3., 4., 5., 6., 3.])

In [39]:
np.array([[1,2] , [3,4]])

array([[1, 2],
       [3, 4]])

In [40]:
a= np.array([3,4,5,6,3.0])
a1=np.array([[1,2] , [3,4]])

In [41]:
a1

array([[1, 2],
       [3, 4]])

In [44]:
a1[1][1]

4

In [45]:
a

array([3., 4., 5., 6., 3.])

In [46]:
a[1]

4.0

In [50]:
a2 =np.array([1,2,3,4],ndmin = 4)

In [54]:
a2[0][0][0][0]

1

In [58]:
a1

array([[1, 2],
       [3, 4]])

In [60]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [61]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [62]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [63]:
a= [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [65]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [66]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [67]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [68]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [69]:
np.fromfunction(lambda i,j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [71]:
np.fromfunction(lambda i,j : i*j, (4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [73]:
np.fromfunction(lambda i,j,z : i*j*z, (3,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [75]:
#(3,2)- 3dimension
#(4,3,2)- 3 dimension with 4 pages(depth)
np.fromfunction(lambda i,j,z : i*j*z, (4,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [76]:
np.fromfunction(lambda i , j ,z ,p: i*j*z*p , (4,3,2,2),dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [77]:
a = np.fromfunction(lambda i , j ,z : i*j*z , (4,3,2),dtype = int)

In [78]:
a.ndim

3

In [79]:
a.size

24

In [80]:
a.shape

(4, 3, 2)

In [81]:
a.dtype

dtype('int32')

In [84]:
a= np.fromfunction(lambda i,j : i*j, (4,3),dtype=int)

In [85]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [86]:
a= np.fromfunction(lambda i,j : i*j, (400,300),dtype=int)

In [87]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9    ...     290  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     290   
2      0    2    4     6     8    10    12    14    16    18  ...     580   
3      0    3    6     9    12    15    18    21    24    27  ...     870   
4      0    4    8    12    16    20    24    28    32    36  ...    1160   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  114550   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  114840   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  115130   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  115420   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  115710   

        291     292     293     294     295     296     297     298     299  
0         0       0       0       0       0       0       0       0       0  
1       291     292     293     294     295     296     297     298     299  
2       582     584     586     588     590     592     594     596     598  
3       873     876     879     882     885     888     891     894     897  
4      1164    1168    1172    1176    1180    1184    1188    1192    1196  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  114945  115340  115735  116130  116525  116920  117315  117710  118105  
396  115236  115632  116028  116424  116820  117216  117612  118008  118404  
397  115527  115924  116321  116718  117115  117512  117909  118306  118703  
398  115818  116216  116614  117012  117410  117808  118206  118604  119002  
399  116109  116508  116907  117306  117705  118104  118503  118902  119301  

[400 rows x 300 columns]

In [88]:
np.random.rand(100,4)

array([[1.08971220e-01, 9.58523475e-01, 6.74884850e-01, 9.19436565e-01],
       [8.37451101e-01, 4.01374844e-01, 7.29373019e-01, 9.58918758e-01],
       [5.20015840e-01, 1.30399060e-01, 7.72611635e-01, 2.42385680e-01],
       [4.79427267e-01, 3.77589402e-01, 7.80657074e-01, 6.82651134e-01],
       [9.25463462e-01, 8.19839495e-01, 7.71316888e-01, 5.71706434e-01],
       [6.64206529e-01, 1.71515349e-01, 9.18858326e-01, 3.16337852e-01],
       [2.95659472e-01, 9.58689934e-01, 7.75801663e-01, 6.50340765e-01],
       [3.39992697e-01, 5.43541485e-01, 8.61215777e-01, 8.67088678e-02],
       [6.32438558e-01, 8.10218418e-01, 2.88667447e-01, 7.70082570e-01],
       [6.61597565e-01, 4.77152146e-02, 8.09943619e-02, 9.00186929e-01],
       [9.57494820e-01, 9.43798611e-01, 2.81812398e-02, 5.89948106e-01],
       [8.85278632e-01, 9.67571762e-01, 4.08656018e-01, 2.80309267e-01],
       [5.35438148e-02, 3.25619048e-01, 9.14276065e-01, 9.17456358e-01],
       [3.62634735e-01, 3.78049141e-01, 6.32743539e

In [91]:
np.random.randint(4,50)

10

In [92]:
np.random.randn(4,5)

array([[ 0.08228813, -0.47500804,  1.11244116, -1.31811366, -0.07692883],
       [-1.59899105,  0.86667669,  0.22845074,  1.49766212,  0.71618068],
       [ 0.33434242,  0.28249916,  1.46399448, -1.01506148, -1.10987682],
       [ 0.91680047,  0.99117948, -0.85510969, -1.26603698,  0.19722806]])

In [93]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.640714  0.625173  1.179923 -0.145560 -1.545071
1 -1.935795 -0.042975  1.692796  1.113015  1.051679
2 -1.121466  1.470558 -0.061274 -0.453643  0.594906
3  1.592033  0.801187 -0.234164  0.476105  0.345778

In [94]:
a = np.fromfunction(lambda i , j ,z : i*j*z , (4,3,2),dtype = int)

In [96]:
a.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [97]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [98]:
pd.DataFrame(a.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [101]:
a.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [102]:
a.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [103]:
a.reshape(4,2,-23543)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4]],

       [[0, 0, 0],
        [3, 0, 6]]])

In [105]:
a.reshape(2,6,-143)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4],
        [0, 0],
        [0, 3],
        [0, 6]]])

In [108]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [109]:
list(range(4,10,2))

[4, 6, 8]

In [115]:
a= np.arange(4,10,.2)

In [114]:
np.arange(4,50.5,5)

array([ 4.,  9., 14., 19., 24., 29., 34., 39., 44., 49.])

In [116]:
a1

array([[1, 2],
       [3, 4]])

In [117]:
a[2:5]

array([4.4, 4.6, 4.8])

In [118]:
arr=np.random.rand(4,5)

In [119]:
arr

array([[0.72519748, 0.1679926 , 0.02216364, 0.974014  , 0.93446421],
       [0.00545133, 0.08854225, 0.32789836, 0.00813167, 0.9900621 ],
       [0.03591732, 0.29198354, 0.40692528, 0.93975709, 0.91363444],
       [0.9320167 , 0.83547139, 0.00344742, 0.60920586, 0.45471135]])

In [122]:
arr[arr>0.5]

array([0.72519748, 0.974014  , 0.93446421, 0.9900621 , 0.93975709,
       0.91363444, 0.9320167 , 0.83547139, 0.60920586])

In [125]:
arr[[1,2],[2]]

array([0.32789836, 0.40692528])

In [126]:
arr= np.random.rand(8,5)

In [127]:
arr

array([[0.00163942, 0.22844669, 0.34223221, 0.22762617, 0.83608908],
       [0.13851168, 0.77339221, 0.83822317, 0.58353572, 0.2182273 ],
       [0.8357334 , 0.24717675, 0.37856846, 0.59687565, 0.74250614],
       [0.99284671, 0.08922041, 0.45958427, 0.04662041, 0.33463444],
       [0.08216314, 0.88833452, 0.18620822, 0.46439111, 0.56158906],
       [0.75259337, 0.86060618, 0.7613289 , 0.55740426, 0.65517584],
       [0.78587441, 0.07658253, 0.05905594, 0.41917812, 0.97632356],
       [0.67394664, 0.57772824, 0.63322493, 0.38606893, 0.41894261]])

In [129]:
arr[1:8, 0:2]

array([[0.13851168, 0.77339221],
       [0.8357334 , 0.24717675],
       [0.99284671, 0.08922041],
       [0.08216314, 0.88833452],
       [0.75259337, 0.86060618],
       [0.78587441, 0.07658253],
       [0.67394664, 0.57772824]])

In [130]:
a2 = arr[1:8 , [0,1,2]]

In [131]:
a2

array([[0.13851168, 0.77339221, 0.83822317],
       [0.8357334 , 0.24717675, 0.37856846],
       [0.99284671, 0.08922041, 0.45958427],
       [0.08216314, 0.88833452, 0.18620822],
       [0.75259337, 0.86060618, 0.7613289 ],
       [0.78587441, 0.07658253, 0.05905594],
       [0.67394664, 0.57772824, 0.63322493]])

In [135]:
a2[0][0]=123

In [136]:
a2

array([[1.23000000e+02, 7.73392207e-01, 8.38223172e-01],
       [8.35733404e-01, 2.47176754e-01, 3.78568463e-01],
       [9.92846709e-01, 8.92204134e-02, 4.59584270e-01],
       [8.21631402e-02, 8.88334521e-01, 1.86208218e-01],
       [7.52593371e-01, 8.60606182e-01, 7.61328897e-01],
       [7.85874409e-01, 7.65825320e-02, 5.90559364e-02],
       [6.73946639e-01, 5.77728244e-01, 6.33224925e-01]])

In [137]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [138]:
a*b

array([[ 2,  6],
       [12, 20]])

In [139]:
a@b

array([[10, 13],
       [22, 29]])

In [140]:
m=a@b

In [141]:
m/0

C:\Users\lerin\AppData\Local\Temp\ipykernel_12252\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])