In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,54]

In [4]:
np.asarray(l)

array([ 1,  2,  3,  4, 54])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
np.empty((4,5))

array([[1.07375789e-311, 1.07375790e-311, 1.07375787e-311,
        1.07375789e-311, 1.07375789e-311],
       [1.07375790e-311, 1.07375789e-311, 1.07375789e-311,
        1.07375781e-311, 1.07375790e-311],
       [1.07375785e-311, 1.07375787e-311, 1.07375789e-311,
        1.16568549e+253, 7.49511203e+247],
       [1.12284826e+219, 1.94919754e-153, 8.76730942e+252,
        2.59903831e-144, 2.22522663e-306]])

In [14]:
np.empty((5,4,2))

array([[[ 0.00000000e+000,  6.95304271e-310],
        [ 1.45255300e-321,              nan],
        [ 7.58328320e-302,  2.67674880e-297],
        [ 3.01331943e-282,  2.04560526e-277]],

       [[ 2.88217829e+002,  2.13451447e-287],
        [ 2.78286850e-307,  2.85163880e-210],
        [ 2.13451447e-287,  1.64294084e-287],
        [ 3.01288598e-282,  3.01628619e-282]],

       [[ 5.11783286e-307, -1.48541028e-065],
        [ 1.54303069e-065, -1.26967865e-277],
        [ 2.49499309e-306,  3.38553712e-301],
        [ 4.62706591e-273,  5.11767330e-307]],

       [[ 1.38774107e-272,  1.38774107e-272],
        [ 1.10830327e-253,  1.39069238e-309],
        [ 1.75380122e-292,  1.07190753e-296],
        [ 5.72844698e-263,  4.68710690e-243]],

       [[ 3.41529431e-291,  1.67548547e-309],
        [ 2.50642605e-292,  1.78438593e-306],
        [ 3.48069273e-308,  2.58046969e-263],
        [ 1.39909626e-309,  1.30082730e-258]]])

In [16]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [17]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [18]:
np.linspace(2,6,10, endpoint=False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [19]:
np.linspace(2,6,10, endpoint=False, retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [20]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [21]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [24]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
a.max()

15

In [26]:
a = np.arange(4,40).reshape(3,6,2)

In [27]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [28]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [29]:
a = np.arange(4,40).reshape(6,6)

In [30]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [31]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [32]:
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [33]:
10+a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [35]:
a/0

C:\Users\lerin\AppData\Local\Temp\ipykernel_23688\4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [36]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [37]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [40]:
b = np.array([2,3,1,2,3,4])
b

array([2, 3, 1, 2, 3, 4])

In [39]:
a+b

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [43]:
b = b.reshape(1,-1)
b

array([[2, 3, 1, 2, 3, 4]])

In [45]:
b.T +a

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [38, 39, 40, 41, 42, 43]])

In [46]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [47]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [48]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [49]:
x = np.array([1,2,3])

In [50]:
y=x

In [51]:
y

array([1, 2, 3])

In [52]:
z = np.copy(x)

In [53]:
z

array([1, 2, 3])

In [54]:
x[0]=100

In [55]:
y

array([100,   2,   3])

In [56]:
z

array([1, 2, 3])

In [57]:
id(z)

2173320838672

In [58]:
id(x)

2173323149456

In [59]:
id(y)

2173323149456

In [60]:
x

array([100,   2,   3])

In [61]:
id(x[0])

2173323370640

In [62]:
y

array([100,   2,   3])

In [63]:
id(y[0])

2173323370896

In [64]:
id([x[1]])

2173323280896

In [65]:
id(y[1])

2173323371216

In [66]:
id(z[1])

2173323371024

In [67]:
h =  np.array([567,345])

In [68]:
df =h

In [69]:
id(h)

2173323306448

In [70]:
id(df)

2173323306448

In [76]:
id(h[0])

2173323372080

In [75]:
id(df[0])

2173323371984

In [77]:
id(h[1])

2173323372176

In [78]:
id(df[1])

2173323371280

In [79]:
id(h[1]) == id(df[1])

True

In [80]:
id(h[0]) == id(df[0])

True

In [81]:
id(h)== id(df)

True

In [82]:
id(h[1]) == id(df[0])

True

In [83]:
x = np.array([34,67,89])

In [85]:
id(x[0]) == id(h[0])

True